### PR TITLE
Changes to the way TemplateVar is handled

### PR DESCRIPTION
**Pull request by alexvandesande**

### CODE REVIEW

**Comment by hiddentao** [comment]
Looks good, though it looks there are merge conflicts that need to be resolved. Plus in the template itself I have fixed the `type` attribute (was supposed to say `title`).

**Comment by alexvandesande** [comment]
Changed the title issue. Not sure which merge issues are there but will merge them myself then, since the purpose of this PR was just to give feedback on the templateVar

**Comment by hiddentao** [comment]
@alexvandesande In ethereum/mist#559 I changed the title attribute values and the inner text to all be using i18n. I'm surprised you didn't get any merge conflicts that way.

**Comment by alexvandesande** [comment]
Oh I did. Haven't uploaded the templatevar changes yet..

**Pull request closed without merging**
